### ISSUE TITLE
All of the <head>'s scripts are gone

### ISSUE THREAD

**Issue by thedanielius** [hunghg255/rsbuild-plugin-react-inspector#2]
Hey, very neat plugin you made here.

However, there is an issue where all of the scripts of <head> tag are missing if this plugin is added.

Scenario: add GTM script to index html <head> and enable this plugin. The script will not longer be there.

**Comment by hunghg255** [comment]
@thedanielius hi, thanks for fb, I think the problem is here

```
     api.modifyRsbuildConfig((config) => {
        const tags: any = config?.html?.tags || [];
        config.html = {
          tags: [
            ...tags,
            {
              tag: 'script',
              head: true,
              attrs: {
                type: 'module',
                src: `http://localhost:${port}/virtual-react-inspector-path-load.js`,
              },
            },
          ],
        };

        return config;
      });
```

I will check later

**Comment by hunghg255** [comment]
I fixed this at https://github.com/hunghg255/rsbuild-plugin-react-inspector/commit/8c10fa7
@thedanielius
