### ISSUE TITLE
Suggestion: option to define Inspector's element position

### ISSUE THREAD

**Issue by thedanielius** [hunghg255/rsbuild-plugin-react-inspector#3]
Hey, me again.

Everything works fine after latest update but I have a suggestion.

Passing an option of element's position to plugin's options. This would result in more dynamic way of placing the element because sometimes it overlaps crucial parts of consumer.

I can suggest a fix later for this if you wish.

**Comment by hunghg255** [comment]
@thedanielius yea, I got it,  welcome PR if you free time.

**Comment by thedanielius** [comment]
Added [PR](https://github.com/hunghg255/rsbuild-plugin-react-inspector/pull/4/files)

Let me know if you like the idea
